# Generated by Django 6.0.1 on 2026-01-14 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_role_alter_administrator_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='role',
        ),
    ]
