# Generated by Django 6.0.1 on 2026-01-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_remove_booking_booking_report_booking_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.IntegerField(default=True),
        ),
    ]
