# Generated by Django 6.0.1 on 2026-01-26 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_booking_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='student',
        ),
    ]
