# Generated by Django 6.0.1 on 2026-02-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_remove_hostel_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
    ]
