"""
Django settings for hostel_management_system project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

from pathlib import Path
import os


BASE_DIR = Path(__file__).resolve().parent.parent


# Local development defaults
SECRET_KEY = 'django-insecure-^j!il64pw7(^o(e4b86y8z)mtn8j3skc3a%-er%*#(7t#3n&%_'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'BackEnd.management',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BackEnd.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BackEnd.wsgi.application'
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'hostel_db',
        'USER': 'postgres',
        'PASSWORD': 'Masoud2002!',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# STATIC_URL = 'static/'
# STATIC_DIR = BASE_DIR / 'static'
# STATICFILES_DIRS = [STATIC_DIR] if STATIC_DIR.exists() else []
# STATIC_ROOT = BASE_DIR / 'staticfiles'


# CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'False').strip().lower() in {'1', 'true', 'yes', 'on'}
# LOCAL_ORIGINS = [
#     'http://localhost:5173',
#     'http://127.0.0.1:5173',
#     'http://localhost:5175',
#     'http://127.0.0.1:5175',
#     'http://localhost:8000',
#     'http://127.0.0.1:8000',
# ]
# _origins_env = os.getenv('CORS_ALLOWED_ORIGINS', '')
# CORS_ALLOWED_ORIGINS = [o.strip() for o in _origins_env.split(',') if o.strip()] if _origins_env else LOCAL_ORIGINS
# CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS
# CORS_ALLOW_CREDENTIALS = True

# SESSION_COOKIE_SECURE = False if DEBUG else True
# CSRF_COOKIE_SECURE = False if DEBUG else True
# SESSION_COOKIE_SAMESITE = 'Lax' if DEBUG else 'None'
# CSRF_COOKIE_SAMESITE = 'Lax' if DEBUG else 'None'
# SECURE_SSL_REDIRECT = False if DEBUG else True
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# LOGIN_URL = 'login'
# LOGIN_REDIRECT_URL = 'home'
# LOGOUT_REDIRECT_URL = 'login'


# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

CORS_ALLOW_ALL_ORIGINS = True  # for testing with Postman

STATIC_ROOT = BASE_DIR/'staticfiles'


SPECTACULAR_SETTINGS = {
    "TITLE": "My Project API",
    "DESCRIPTION": "API for My Project",
    "VERSION": "1.0.0",
    # "SERVE_INCLUDE_SCHEMA": False,   # tweak options here
}