# Generated by Django 6.0.1 on 2026-01-14 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_administrator_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.role'),
        ),
    ]
