# Generated by Django 6.0.1 on 2026-01-15 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_rename_pho_administrator_phone_booking_hostel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_report',
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.IntegerField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='hostel',
            name='hostel_owner',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='management.hostel_owner'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='student',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='management.student'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
